const KEY="ileriaKitchenV1";
const seed={settings:{laborRate:25,targetMargin:.33},ingredients:[],recipes:[]};
const raw=[
["Vegetable Oil",.31,"cup"],["Red Onion",2.52,"lb"],["Red Bell Pepper",1,"unit"],["Jalapeno",.25,"unit"],["Garlic",.75,"unit"],["Ground Cumin",.28,"tsp"],["Kosher Salt",.01,"tsp"],["Black Beans",1/15,"oz"],["Corn (Ear)",.5,"unit"],["Cilantro",10.58,"cup"],["Lime",.5,"unit"],["Flour",.335,"cup"],["Baking Soda",.02,"tsp"],["Baking Powder",.07,"tsp"],["Ground Ginger",.2933,"tsp"],["Crystalized Ginger",.2033,"tbsp"],["Cinnamon",.31,"tsp"],["Ground Cardamom",.55,"tsp"],["Eggs",.555,"unit"],["Olive Oil",4.8,"cup"],["Light Brown Sugar",1.06,"cup"],["Granulated Sugar",.44,"cup"],["Vanilla Extract",.91,"tsp"],["Orange Zest",.2,"tsp"],["Zucchini",1,"unit"],["Carrott",.5,"cup"],["Butter",2,"cup"],["Pumpkin Puree",3.67/15,"oz"],["Pumpkin Spice",.9933,"tbsp"],["Rolled Oats",.5643,"cup"],["Powdered Sugar",.66,"cup"],["Milk",7/16,"cup"],["Apple Cider",0,"cup"],["Apple Pie Spice",0,"tsp"]];
seed.ingredients=raw.map((x,i)=>({id:"i"+i,name:x[0],costPerUnit:x[1],unit:x[2],supplier:"Seeded from recipe reports",updated:"2026-09-28"}));
function make(name,category,yieldQty,laborMin,rows){return{id:crypto.randomUUID(),name,category,yieldQty,yieldUnit:"pieces",prepMin:laborMin,cookMin:0,prepLabor:true,cookLabor:true,overhead:0,rows:rows.map(x=>({ingredient:x[0],qty:x[1],unit:x[2]}))}}
seed.recipes=[
make("Black Bean and Sautéed Corn","Salad",5,20,[["Vegetable Oil",2,"tbsp"],["Red Onion",.25,"lb"],["Red Bell Pepper",.5,"unit"],["Jalapeno",1,"unit"],["Garlic",1,"unit"],["Ground Cumin",.5,"tsp"],["Kosher Salt",2,"tsp"],["Black Beans",15,"oz"],["Corn (Ear)",3,"unit"],["Cilantro",.5,"cup"],["Lime",2,"unit"]]),
make("Carrot Zucchini Ginger Muffin","Muffin",5,22.5,[["Flour",2,"cup"],["Baking Soda",1,"tsp"],["Baking Powder",1,"tsp"],["Ground Ginger",1.5,"tsp"],["Crystalized Ginger",3,"tbsp"],["Cinnamon",1,"tsp"],["Ground Cardamom",.25,"tsp"],["Kosher Salt",.5,"tsp"],["Eggs",2,"unit"],["Olive Oil",.5,"cup"],["Light Brown Sugar",.5,"cup"],["Granulated Sugar",.25,"cup"],["Vanilla Extract",1,"tsp"],["Orange Zest",1,"tsp"],["Zucchini",1,"unit"],["Carrott",1,"cup"]]),
make("Pumpkin Cardamom Crumb Muffins","Muffin",6,22.5,[["Flour",.75,"cup"],["Light Brown Sugar",.5,"cup"],["Ground Cardamom",1,"tsp"],["Cinnamon",1,"tsp"],["Kosher Salt",1,"tsp"],["Butter",.5,"cup"],["Granulated Sugar",1.75,"cup"],["Vegetable Oil",.5,"cup"],["Vanilla Extract",1,"tsp"],["Eggs",2,"unit"],["Pumpkin Puree",15,"oz"],["Flour",2,"cup"],["Pumpkin Spice",3,"tbsp"],["Ground Cardamom",.5,"tsp"]]),
make("Pumpkin Oatmeal Cookie","Cookies",26,30,[["Butter",1,"cup"],["Light Brown Sugar",.25,"cup"],["Granulated Sugar",.25,"cup"],["Pumpkin Puree",.6,"cup"],["Pumpkin Spice",3,"tsp"],["Vanilla Extract",3,"tsp"],["Kosher Salt",1,"tsp"],["Rolled Oats",1.4,"cup"],["Flour",1,"cup"],["Baking Soda",.5,"tsp"]])];
let db=JSON.parse(localStorage.getItem(KEY)||"null")||seed;
const save=()=>localStorage.setItem(KEY,JSON.stringify(db)),money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n||0),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const vol={tsp:1,tbsp:3,"fl oz":6,cup:48,pint:96,quart:192,gallon:768,ml:.202884,l:202.884},wt={g:1,kg:1000,oz:28.3495,lb:453.592};
function convert(q,a,b){if(a===b)return q;if(vol[a]&&vol[b])return q*vol[a]/vol[b];if(wt[a]&&wt[b])return q*wt[a]/wt[b];if(["unit","each"].includes(a)&&["unit","each"].includes(b))return q;return null}
function ingredient(name){return db.ingredients.find(i=>i.name===name)}
function rowCost(row){const i=ingredient(row.ingredient);if(!i)return 0;const q=convert(+row.qty,row.unit,i.unit);return q==null?0:q*i.costPerUnit}
function calc(r){const ingredients=r.rows.reduce((a,x)=>a+rowCost(x),0),mins=(r.prepLabor?+r.prepMin:0)+(r.cookLabor?+r.cookMin:0),labor=mins/60*db.settings.laborRate,packaging=+r.packaging||0,total=ingredients+labor+packaging+(+r.overhead||0),margin=(r.targetMargin??db.settings.targetMargin),sales=margin>=1?0:total/(1-margin),profit=sales-total;return{ingredients,labor,packaging,total,unit:total/(+r.yieldQty||1),sales,profit,salesUnit:sales/(+r.yieldQty||1),profitUnit:profit/(+r.yieldQty||1),target:sales}}
function dashboard(){const cs=db.recipes.map(calc),avg=cs.length?cs.reduce((a,c)=>a+c.unit,0)/cs.length:0;return '<div class="grid kpis">'+[['Recipes',db.recipes.length],['Ingredients',db.ingredients.length],['Avg. unit cost',money(avg)],['Labor rate',money(db.settings.laborRate)+'/hr']].map(x=>'<div class="card kpi"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></div>').join('')+'</div><div class="grid two"><section class="card"><div class="section-title"><h2>Recipe costs</h2><span class="pill">Live calculations</span></div>'+recipeTable()+'</section><section class="card"><div class="section-title"><h2>Cost checks</h2></div><div class="list">'+db.ingredients.filter(i=>!i.purchasePrice).slice(0,6).map(i=>'<div class="list-item"><strong>'+i.name+'</strong><br><span class="muted">Seeded cost · add package price when ready</span></div>').join('')+'</div></section></div>'}
function recipeTable(){return '<table><thead><tr><th>Recipe</th><th>Yield</th><th>Batch</th><th>Per item</th></tr></thead><tbody>'+db.recipes.map(r=>{const c=calc(r);return '<tr><td><strong>'+r.name+'</strong><br><span class="muted">'+r.category+'</span></td><td>'+r.yieldQty+' '+r.yieldUnit+'</td><td>'+money(c.total)+'</td><td>'+money(c.unit)+'</td></tr>'}).join('')+'</tbody></table>'}
function ingredients(){return '<div class="toolbar"><button class="primary" id="addIngredient">+ Add ingredient</button><button class="secondary" id="exportData">Export JSON</button><label class="secondary">Import JSON<input id="importData" type="file" accept=".json" hidden></label></div><div class="card"><table><thead><tr><th>Ingredient</th><th>Supplier</th><th>Working cost</th><th>Updated</th></tr></thead><tbody>'+db.ingredients.map(i=>'<tr><td><strong>'+i.name+'</strong></td><td>'+i.supplier+'</td><td>'+money(i.costPerUnit)+' / '+i.unit+'</td><td>'+i.updated+'</td></tr>').join('')+'</tbody></table></div>'}
function recipes(){return '<div class="recipe-grid">'+db.recipes.map(r=>{const c=calc(r);return '<div class="card recipe-card" data-id="'+r.id+'"><span class="pill">'+r.category+'</span><h3>'+r.name+'</h3><span class="muted">Makes '+r.yieldQty+' '+r.yieldUnit+'</span><div class="cost">'+money(c.unit)+'</div><span class="muted">cost per item</span></div>'}).join('')+'</div>'}
function reports(){return '<div class="card"><div class="section-title"><h2>Recipe cost analysis</h2><span class="muted">Target margin '+Math.round(db.settings.targetMargin*100)+'%</span></div><table><thead><tr><th>Recipe</th><th>Ingredients</th><th>Labor</th><th>Total</th><th>2×</th><th>3×</th><th>Target margin</th></tr></thead><tbody>'+db.recipes.map(r=>{const c=calc(r);return '<tr><td><strong>'+r.name+'</strong></td><td>'+money(c.ingredients)+'</td><td>'+money(c.labor)+'</td><td>'+money(c.total)+'</td><td>'+money(c.total*2)+'</td><td>'+money(c.total*3)+'</td><td>'+money(c.target)+'</td></tr>'}).join('')+'</tbody></table></div>'}
function settings(){return '<div class="card" style="max-width:650px"><h2>Costing settings</h2><div class="form-grid"><div><label>Labor rate ($ / hour)</label><input id="laborRate" type="number" step=".01" value="'+db.settings.laborRate+'"></div><div><label>Target margin (%)</label><input id="targetMargin" type="number" value="'+db.settings.targetMargin*100+'"></div></div><p class="muted">Changes recalculate every recipe.</p><button class="primary" id="saveSettings">Save settings</button></div>'}
const views={dashboard,ingredients,recipes,reports,settings},titles={dashboard:"Kitchen Dashboard",ingredients:"Ingredient Library",recipes:"Recipes",reports:"Cost Reports",settings:"Settings"};
function render(view="dashboard"){$$("#nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===view));$("#pageTitle").textContent=titles[view];$("#newRecipe").style.display=view==="settings"?"none":"";$("#app").innerHTML=views[view]();bind(view)}
function closeModal(){$("#modal").classList.add("hidden")}
function ingredientModal(){$("#modalBody").innerHTML='<p class="eyebrow">INGREDIENT LIBRARY</p><h2>Add Ingredient</h2><div class="form-grid"><div><label>Name</label><input id="iName"></div><div><label>Supplier / Store</label><input id="iSupplier"></div><div><label>Purchase price ($)</label><input id="iPrice" type="number" step=".01"></div><div><label>Package quantity</label><input id="iQty" type="number" step=".001"></div><div><label>Package unit</label><select id="iUnit">'+units().map(u=>'<option>'+u+'</option>').join('')+'</select></div><div><label>Price date</label><input id="iDate" type="date"></div></div><p class="muted">Working unit cost is derived from package price and size.</p><button class="primary" id="saveIngredient">Save ingredient</button>';$("#modal").classList.remove("hidden");$("#iDate").value=new Date().toISOString().slice(0,10);$("#saveIngredient").onclick=()=>{const p=+$("#iPrice").value,q=+$("#iQty").value,u=$("#iUnit").value;db.ingredients.push({id:crypto.randomUUID(),name:$("#iName").value,supplier:$("#iSupplier").value,purchasePrice:p,packageQty:q,packageUnit:u,unit:u,costPerUnit:q?p/q:0,updated:$("#iDate").value});save();closeModal();render("ingredients")}}
function units(){return["g","kg","oz","lb","ml","l","tsp","tbsp","fl oz","cup","pint","quart","gallon","unit"]}\nfunction yieldUnits(){return["pieces","servings","cookies","muffins","loaves","slices","dozen","trays","cups","oz","lb","g","kg","ml","l"]}
function rowHTML(row){row=row||{ingredient:db.ingredients[0].name,qty:1,unit:"cup"};return '<div class="ingredient-row"><div><label>Ingredient</label><select class="ri">'+db.ingredients.map(i=>'<option '+(i.name===row.ingredient?'selected':'')+'>'+i.name+'</option>').join('')+'</select></div><div><label>Qty</label><input class="rq" type="number" step=".001" value="'+row.qty+'"></div><div><label>Unit</label><select class="ru">'+units().map(u=>'<option '+(u===row.unit?'selected':'')+'>'+u+'</option>').join('')+'</select></div><div class="muted rc"></div><button class="danger removeRow">×</button></div>'}
function recipeModal(existing){const r=existing?JSON.parse(JSON.stringify(existing)):{id:crypto.randomUUID(),name:"",category:"",yieldQty:1,yieldUnit:"pieces",prepMin:0,cookMin:0,prepLabor:true,cookLabor:true,packaging:0,overhead:0,targetMargin:db.settings.targetMargin,rows:[]};$("#modalBody").innerHTML='<p class="eyebrow">RECIPE BUILDER</p><h2>'+(existing?"Edit":"New")+' Recipe</h2><div class="form-grid"><div><label>Name</label><input id="rName" value="'+r.name+'"></div><div><label>Category</label><input id="rCat" value="'+r.category+'"></div><div><label>Batch yield</label><input id="rYield" type="number" value="'+r.yieldQty+'"></div><div><label>Yield unit</label><select id="rYieldUnit">'+yieldUnits().map(u=>'<option '+(u===r.yieldUnit?'selected':'')+'>'+u+'</option>').join('')+'</select></div><div><label>Prep minutes</label><input id="rPrep" type="number" value="'+r.prepMin+'"><label><input id="rPrepLabor" type="checkbox" style="width:auto" '+(r.prepLabor?'checked':'')+'> counts as labor</label></div><div><label>Cook minutes</label><input id="rCook" type="number" value="'+r.cookMin+'"><label><input id="rCookLabor" type="checkbox" style="width:auto" '+(r.cookLabor?'checked':'')+'> counts as labor</label></div><div><label>Packaging / batch ($)</label><input id="rPackaging" type="number" min="0" step=".01" value="'+(r.packaging||0)+'"></div><div><label>Desired profit margin (%)</label><input id="rMargin" type="number" min="0" max="99" step="1" value="'+Math.round((r.targetMargin??db.settings.targetMargin)*100)+'"></div></div><h3>Ingredients</h3><div id="rows">'+r.rows.map(rowHTML).join('')+'</div><button class="secondary" id="addRow">+ Add ingredient</button><div class="summary" id="liveSummary"></div><div style="display:flex;justify-content:flex-end;gap:8px;margin-top:18px">'+(existing?'<button class="danger" id="deleteRecipe">Delete</button>':'')+'<button class="primary" id="saveRecipe">Save recipe</button></div>';$("#modal").classList.remove("hidden");
function collect(){r.name=$("#rName").value;r.category=$("#rCat").value;r.yieldQty=+$("#rYield").value;r.yieldUnit=$("#rYieldUnit").value;r.prepMin=+$("#rPrep").value;r.cookMin=+$("#rCook").value;r.prepLabor=$("#rPrepLabor").checked;r.cookLabor=$("#rCookLabor").checked;r.packaging=+$("#rPackaging").value;r.targetMargin=+$("#rMargin").value/100;r.rows=$$("#rows .ingredient-row").map(el=>({ingredient:el.querySelector(".ri").value,qty:+el.querySelector(".rq").value,unit:el.querySelector(".ru").value}));return r}
function live(){const c=calc(collect());$$("#rows .ingredient-row").forEach((el,i)=>el.querySelector(".rc").textContent=money(rowCost(r.rows[i])));$("#liveSummary").innerHTML='<div><span>Ingredients</span><strong>'+money(c.ingredients)+'</strong></div><div><span>Labor</span><strong>'+money(c.labor)+'</strong></div><div><span>Packaging</span><strong>'+money(c.packaging)+'</strong></div><div><span>Total cost</span><strong>'+money(c.total)+'</strong></div><div><span>Sales needed</span><strong>'+money(c.sales)+'</strong></div><div><span>Total profit</span><strong>'+money(c.profit)+'</strong></div><div><span>Sell each for</span><strong>'+money(c.salesUnit)+'</strong></div><div><span>Profit / item</span><strong>'+money(c.profitUnit)+'</strong></div>'}
$("#modalBody").oninput=live;$("#modalBody").onchange=live;$("#addRow").onclick=()=>{$("#rows").insertAdjacentHTML("beforeend",rowHTML());live()};$("#rows").onclick=e=>{if(e.target.classList.contains("removeRow")){e.target.closest(".ingredient-row").remove();live()}};$("#saveRecipe").onclick=()=>{collect();const i=db.recipes.findIndex(x=>x.id===r.id);if(i>=0)db.recipes[i]=r;else db.recipes.push(r);save();closeModal();render("recipes")};if(existing)$("#deleteRecipe").onclick=()=>{db.recipes=db.recipes.filter(x=>x.id!==r.id);save();closeModal();render("recipes")};live()}
function bind(view){$("#newRecipe").onclick=()=>recipeModal();if(view==="recipes")$$(".recipe-card").forEach(el=>el.onclick=()=>recipeModal(db.recipes.find(r=>r.id===el.dataset.id)));if(view==="ingredients"){$("#addIngredient").onclick=ingredientModal;$("#exportData").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:"application/json"}));a.download="ileria-kitchen-backup.json";a.click()};$("#importData").onchange=e=>{const rd=new FileReader();rd.onload=()=>{db=JSON.parse(rd.result);save();render("ingredients")};rd.readAsText(e.target.files[0])}}if(view==="settings")$("#saveSettings").onclick=()=>{db.settings.laborRate=+$("#laborRate").value;db.settings.targetMargin=+$("#targetMargin").value/100;save();render("settings")}}
$("#nav").onclick=e=>{if(e.target.dataset.view)render(e.target.dataset.view)};$("#closeModal").onclick=closeModal;$("#modal").onclick=e=>{if(e.target.id==="modal")closeModal()};render();